package ar.edu.unlam.pb2.eva03.enumeradores;

public enum TipoDeEvento {

	CARRERA_5K,
	CARRERA_10K,
	CARRERA_21K,
	CARRERA_42K,
	DUATLON,
	CARRERA_NATACION_EN_PICINA,
	CARRERA_NATACION_EN_AGUAS_ABIERTAS,
	TRIATLON_SHORT,
	TRIATLON_OLIMPICO,
	TRIATLON_MEDIO,
	TRIATLON_IRONMAN
}
